[[anime]]
name = "夏日重现"
url = "https://share.dmhy.org/topics/rss/rss.xml?keyword=%E5%A4%8F%E6%97%A5%E9%87%8D%E7%8E%B0+1080P&sort_id=0&team_id=288&order=date-desc"

[[anime]]
name = "神墓"
url = "https://share.dmhy.org/topics/rss/rss.xml?keyword=%E7%A5%9E%E5%A2%93+4k&sort_id=0&team_id=755&order=date-desc"

[[anime]]
name = "契约之吻"
url = "https://share.dmhy.org/topics/rss/rss.xml?keyword=%E5%A5%91%E7%BA%A6%E4%B9%8B%E5%90%BB+mp4&sort_id=0&team_id=801&order=date-desc"

[[anime]]
name = "异世界舅舅"
url = "https://share.dmhy.org/topics/rss/rss.xml?keyword=%E5%BC%82%E4%B8%96%E7%95%8C%E8%88%85%E8%88%85+Big5+1080&sort_id=0&team_id=241&order=date-desc"
