[[anime]]
name = "师兄啊师兄"
url = "https://share.dmhy.org/topics/rss/rss.xml?keyword=%E5%B8%88%E5%85%84%E5%95%8A%E5%B8%88%E5%85%84&sort_id=0&team_id=755&order=date-desc"

[[anime]]
name = "异世界舅舅"
url = "https://share.dmhy.org/topics/rss/rss.xml?keyword=%E5%BC%82%E4%B8%96%E7%95%8C%E8%88%85%E8%88%85+Big5+1080&sort_id=0&team_id=241&order=date-desc"
